In [65]:
import nltk
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer
import functools
import pandas as pd

In [29]:
texto = """In sum I’m a geek interested in the social, in culture and politics. 
I have inherited a hands on mood from the BA in Graphic Design I hold. 
My passion for technology introduced me the idea of hacking."""
# fonte: http://cuducos.me/

# split + Counter

In [62]:
split_counter = Counter(texto.split())

# nltk.word_tokenize + Counter

In [63]:
nltk_counter = Counter(nltk.word_tokenize(texto, language='portuguese'))

# scikit-learn.feature_extraction.text.CountVectorizer

In [56]:
cv = CountVectorizer(tokenizer=functools.partial(nltk.word_tokenize, language='portuguese'), lowercase=False)
texto_cv = cv.fit_transform([texto]).todense()

In [64]:
sk_counter = dict(zip(cv.get_feature_names(), texto_cv.tolist()[0]))

# Comparando

In [66]:
df = pd.DataFrame({'split_counter': split_counter, 'nltk_counter': nltk_counter, 'sk_counter': sk_counter})

In [67]:
df

            nltk_counter  sk_counter  split_counter
,                      1           1            NaN
.                      3           3            NaN
BA                     1           1              1
Design                 1           1              1
Graphic                1           1              1
I                      2           2              2
In                     1           1              1
I’m                    1           1              1
My                     1           1              1
a                      2           2              2
and                    1           1              1
culture                1           1              1
for                    1           1              1
from                   1           1              1
geek                   1           1              1
hacking                1           1            NaN
hacking.             NaN         NaN              1
hands                  1           1              1
have                   1           1              1
hold                   1           1            NaN
hold.                NaN         NaN              1
idea                   1           1              1
in                     3           3              3
inherited              1           1              1
interested             1           1              1
introduced             1           1              1
me                     1           1              1
mood                   1           1              1
of                     1           1              1
on                     1           1              1
passion                1           1              1
politics               1           1            NaN
politics.            NaN         NaN              1
social                 1           1            NaN
social,              NaN         NaN              1
sum                    1           1              1
technology             1           1              1
the                    3           3              3